apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-collector
  labels:
    app: collector
spec:
  type: {{ .Values.service.type }}
  selector:
    app: collector
  ports:
    - name: otlp-http
      port: {{ .Values.service.port }}
      targetPort: otlp-http
